logging:
  level:
    com:
      netflix: ERROR
    org:
      apache:
        http: INFO
        juli: ERROR
      hibernate: ERROR
      springframework: INFO
      springframework.jmx: ERROR
      springframework.test: ERROR
      springframework.web.servlet.handler: ERROR
spring:
  profiles:
    active: ${active_profile:local}
  application:
    name: InvoiceWebApp
  datasource:
    default-auto-commit: true
    initial-size: 5
    max-active: 10
    min-idle: 7
    driver-class-name: com.mysql.cj.jdbc.Driver
  jmx:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  main:
    banner-mode: 'off'
