spring:
    datasource:
        url: jdbc:mysql://localhost:3306/invoice_web_app1?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2
        username: root
        password: root