logging:
  level:
    com:
      netflix: ERROR
    org:
      apache:
        http: INFO
        juli: ERROR
      hibernate: ERROR
      springframework: INFO
      springframework.jmx: ERROR
      springframework.test: ERROR
      springframework.web.servlet.handler: ERROR


spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  profiles:
    active: ${active_profile:local}
  application:
    name: InvoiceWebApp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jmx:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  main:
    banner-mode: 'off'
